### ISSUE TITLE
plugins:install error

### ISSUE THREAD

**Issue by zhangpeihao** [heroku/heroku-deploy#27]
D:\tmp\heroku>heroku plugins:install https://github.com/heroku/heroku-deploy
Installing heroku-deploy... failed
 !    Could not install heroku-deploy. Please check the URL and try again.

D:\tmp\heroku>heroku version
heroku/toolbelt/3.2.2 (i386-mingw32) ruby/1.9.3

**Comment by jkutner** [comment]
Does this still happen? It should be fixed in the latest version of the plugin. Let us know if it is not.

**Comment by Sheparzo** [comment]
I'm getting this same error
