### ISSUE TITLE
no mention about deploy:jar function in README.md

### ISSUE THREAD

**Issue by bigwheel** [heroku/heroku-deploy#31]
https://github.com/heroku/heroku-deploy/blob/master/lib/heroku/command/deploy.rb#L67-L113

This is very useful, I seek this way in almost 2days.
Please add it to doc, i guess many developers want it.

**Comment by jkutner** [comment]
Done! sorry for the trouble:
https://github.com/heroku/heroku-deploy/blob/master/README.md

**Comment by bigwheel** [comment]
thanks :)
