### ISSUE TITLE
plugin:install fails

### ISSUE THREAD

**Issue by Sheparzo** [heroku/heroku-deploy#35]
I'm getting an error while trying to install the plugin:
`$ heroku plugins:install https://github.com/heroku/heroku-deploy
Installing https://github.com/heroku/heroku-deploy... failed
 !    Could not install heroku-deploy. Please check the URL and try again.`

**Comment by ransombriggs** [comment]
@Sheparzo That error happens whenever the git clone fails.  Could you please try and clone that url and see if there is an error that is preventing this from being cloned on your machine?

**Comment by Sheparzo** [comment]
Thanks @ransombriggs.  I had an environment issue that was preventing me from cloning anything.  It's fixed and I am good.  Closing.
