### ISSUE TITLE
I could not pass Procfile with jar to Heroku's free dyno.

### ISSUE THREAD

**Issue by mielecmichal** [heroku/heroku-deploy#38]
I run following commands from directory containing both .jar and Procfile:
```
heroku create appName --no-remote
heroku deploy:jar appName.jar  --app appName
```
but ```heroku ps --app appName``` shows default run command all the time:
```java $JAVA_OPTS -jar appName.jar  $JAR_OPTS```

```heroku deploy:jar appName.jar  --app appName -i Procfile``` also doesn't work.

My Procfile is: ```web java -jar appName.jar --server.port=$PORT``` and application is Spring Boot based.

**Comment by jkutner** [comment]
Try running:

```
heroku deploy:jar --jar appName.jar  --app appName
```

We've just ported [heroku-deploy](https://github.com/heroku/heroku-deploy) plugin over to a new plugin called [heroku-cli-deploy](https://github.com/heroku/heroku-cli-deploy). heroku-cli-deploy support the command *without* the `--jar` option, but this plugin requires it.

Can you tell me the path you followed to get here? I wonder if there is some documentation that is still incorrect (we had to update a lot). Thanks.

**Comment by mielecmichal** [comment]
I found this repo by googling "heroku deploy:jar" which is in my browser on 5th position :)

After ```heroku deploy:jar --jar appName.jar  --app appName```
```heroku ps``` still shows default run command.

I have installed newest version so I close this issue and move to https://github.com/heroku/heroku-cli-deploy/issues/2:
```
heroku plugins
=== Installed Plugins
heroku-cli-deploy@0.1.2

```
